### ISSUE TITLE
NullPointerException as googleCloudProjectNumber is passed as Integer but parsed as Long

### ISSUE THREAD

**Issue by mariovoelker** [capacitor-community/play-integrity#2]
**Describe the bug**
Thank you for this Plugin. I found the following bug in my local setup.

The `data` JSONObject property of `PluginCall`, passed into `requestIntegrityToken` is treated as Integer so the `call.getLong("googleCloudProjectNumber")` produces a NullPointerException

**To Reproduce**
1. In the capacitor app, call 
```
await PlayIntegrity.requestIntegrityToken({
      nonce: crypto.randomUUID(),
      googleCloudProjectNumber: 0,
    });
```
3. Run `ionic cap sync`
5. Run the Android app
6. See error on startup:
```
Serious error executing plugin
 java.lang.reflect.InvocationTargetException
 at java.lang.reflect.Method.invoke(Native Method)
 at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
 at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:816)
 at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
 at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.os.HandlerThread.run(HandlerThread.java:67)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
```
**Expected behavior**
Use the `int` value passed. Potentially the `googleCloudProjectNumber` JSON property could be String typed and the String parsed to long.

**Screenshots**
<img width="800px" alt="Screenshot 2024-05-16 at 16 58 42" src="https://github.com/capacitor-community/play-integrity/assets/1242485/d886a1bb-58d0-4e6e-bc0a-ab4dbc7e6760">
<br/>
<img width="600px" alt="JSON Object with Integer property" src="https://github.com/capacitor-community/play-integrity/assets/1242485/a3f82983-3fc8-4bd3-8d3b-4b6f58cc633f">
<br/>
<img width="300px" alt="is instanceOf Integer true" src="https://github.com/capacitor-community/play-integrity/assets/1242485/52b4477a-6ad6-4671-9669-fc3dcfb83f7d">
<br/>
<img width="300px" alt="is instanceOf Long false" src="https://github.com/capacitor-community/play-integrity/assets/1242485/22253405-da60-4aee-8c54-6e22b514c58f">

**Smartphone (please complete the following information):**
 - Device: Nexus 7 API 33 (Emulator)
 - OS: Android 13 (Tiramisu) 
 - Capacitor-version: 6.0.0
 - Typescript-version: 5.4.5

**Comment by ashishzv** [comment]
await PlayIntegrity.requestIntegrityToken({
      nonce: crypto.randomUUID(),
      googleCloudProjectNumber: 1234545668434  ,
    });

pass your actual googleCloudProjectNumber instance of 0
